### PR TITLE
All solutions

### PR DESCRIPTION
**Pull request by mayannaj**

### CODE REVIEW

**Comment by nwjnsttr** [comment]
Does "all solutions" mean that it's going to print all solutions instead of the first one?

**Comment by mayannaj** [comment]
Yes that's correct.

**Comment by nwjnsttr** [comment]
Did you run the code to make sure it works?

**Comment by mayannaj** [comment]
Yes it runs perfectly fine.

**Comment by nwjnsttr** [comment]
Okay, merging them.

**Pull request merged**
